snowflake_conn_prop = {
   "account": "wf55094.ap-southeast-1",
    "user": "SHETTY21",
    "password": "Se@9869655005",
   "role": "ACCOUNTADMIN",
   "database": "Demo",
   "schema": "PUBLIC",
   "warehouse": "COMPUTE_WH",
}